apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "my-app.fullname" . }}-destination
  namespace: default
spec:
  host: {{ include "my-app.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2